### ISSUE TITLE
How do you develop with Roswell ?

### ISSUE THREAD

**Issue by vindarel** [koji-kojiro/cl-repl#20]
Hi,

What is your current setup to test cl-repl with roswell ?

I would like to test modifications done in `cl-repl.ros`. When I run `./cl-repl.ros`, Quicklisp will not load my cl-repl which is in `quicklisp/local-projects/` :/ I checked that it is referenced in `system-index.txt`.

I also tried to change the shebang to

```
#!/bin/sh
#|-*- mode:lisp -*-|#
#| A repl implementation of Common Lisp
exec ros -Q  -- $0 "$@"
|#
```

(maybe bypassing roswell cache?) to no avail.

Can you just tell how you do ? (and add a note in the readme or a contributing file ?)

Thanks.

**Comment by koji-kojiro** [comment]
Just clone this repo into `∼/.roswell/local-projects/`
Something like: `∼/.roswell/local-projects/koji-kojiro/cl-repl`

I'm not sure but, you may also need to update `system-index.txt`, as follows.

```
CL-USER> (ql:register-local-projects)
NIL
```

**Comment by koji-kojiro** [comment]
Hi, @vindarel 
Have you solved this?
Can I close this issue?

**Comment by vindarel** [comment]
Yes I'm good thanks.

(I was disturbed by print statements that would be printed at the program termination… and then remembered `finish-output`)

(edit) actually I encountered another peculiar thing. Roswell uses a different quicklisp dist and local projects than the system. So if I quickload a library in Slime, it will be installed by default in quicklisp/local-projects, and the library being developed into `.roswell/local-projects` won't find it. I know we have to set up Slime to use Roswell as explained [here](https://github.com/roswell/roswell/wiki/Initial-Recommended-Setup) (I didn't need it so far, I would like to avoid it if possible and it is indeed possible to develop cl-repl without the roswell machinery).

**Comment by koji-kojiro** [comment]
How about creating a symlink?
