### ISSUE TITLE
Lock on package COMMON-LISP violated when setting the value of VALUES while in package COMMON-LISP-USER.

### ISSUE THREAD

**Issue by m-bob** [koji-kojiro/cl-repl#36]
I'm new to common lisp and sbcl, so this issue may not have anything to do with cl-repl. However, when I directly invoke sbcl, the issue does not occur.

I'm on a Macbook Pro, running OS X 10.11.6. I have SBCL 1.3.18 installed.

When I invoke cl-repl, it starts without any obvious problems. However, if I type in a lisp expression, such as (+ (* 3 5) 4), I immediately get an error message that I've violated a lock in COMMON-LISP-USER. I can cure that error (on a session basis, by choosing restart-2), but a better solution would be preferred.

Here's what happens:

06:57:00 ~ 501 >  cl-repl
  ___  __          ____  ____  ____  __
 / __)(  )    ___ (  _ \(  __)(  _ \(  )
( (__ / (_/\ (___) )   / ) _)  ) __// (_/\
 \___)\____/      (__\_)(____)(__)  \____/
cl-repl 0.5.0 on Roswell 18.1.10.87, SBCL 1.4.4
(C) 2017-2018 TANI Kojiro <kojiro0531@gmail.com>

CL-USER> (+ (* 3 5) 4)
Lock on package COMMON-LISP violated when setting the value of VALUES while in
package COMMON-LISP-USER.
See also: The SBCL Manual, Node "Package Locks" The ANSI Standard, Section 11.1.2.1.2
 [Condition of type SYMBOL-PACKAGE-LOCKED-ERROR]

Restarts:
 0: [CONTINUE] Ignore the package lock.
 1: [IGNORE-ALL] Ignore all package locks in the context of this operation.
 2: [UNLOCK-PACKAGE] Unlock the package.
 3: [*ABORT] Deduce debugger level.
 4: [*EXIT] Exit CL-REPL.
 5: [*RETRY] Try evaluating again.
 6: [RETRY] Retry EVAL of current toplevel form.
 7: [CONTINUE] Ignore error and continue loading file NIL.
 8: [ABORT] Abort loading file NIL.
 9: [CONTINUE] Ignore runtime option --eval "(ros:run '((:eval\"(ros:quicklisp)\")(:script \"/Users/murray/.roswell/bin/cl-repl\")(:quit ())))".
10: [ABORT] Skip rest of --eval and --load options.
11: [ABORT] Skip to toplevel READ/EVAL/PRINT loop.
12: [EXIT] Exit SBCL (calling #'EXIT, killing the process).

Usage:
  Ctrl+r: select restart. Ctrl+t: show backtrace.

[1]CL-USER>
Restart number:
[OUT]: 19
CL-USER>

Here's the backtrace:

[1]CL-USER>
Date/time: 2018-02-22-11:33An unhandled error condition has been signalled:
                              Lock on package COMMON-LISP violated when
                              setting the value of VALUES while in package
                              COMMON-LISP-USER.
See also:
  The SBCL Manual, Node "Package Locks"
  The ANSI Standard, Section 11.1.2.1.2

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10005505B3}>
0: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE-TO-STREAM #<SYNONYM-STREAM :SYMBOL *TERMINAL-IO* {100001FC63}>)
1: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE #<SYMBOL-PACKAGE-LOCKED-ERROR "setting the value of ~S" {1004FC3873}> :OUTPUT NIL :IF-EXISTS :APPEND :VERBOSE NIL)
2: (CL-REPL::SHOW-BACKTRACE #<unused argument> #<unused argument>)
3: ((LAMBDA (#:G62 #:G63) :IN CL-READLINE:BIND-KEYSEQ) 1 20)
4: ((LAMBDA (SB-ALIEN::ARGS-POINTER SB-ALIEN::RESULT-POINTER FUNCTION) :IN CL-READLINE:BIND-KEYSEQ) #<unavailable argument> #<unavailable argument> #<unavailable argument>)
5: ("foreign function: funcall_alien_callback")
6: ("foreign function: #x20100407")
7: (CL-REPL::READ-INPUT)
8: (CL-REPL::READ-EVAL-PRINT)
9: (CL-REPL::REPL :PACKAGE #<unused argument> :LEVEL 1 :KEYMAP "debugger")
10: (CL-REPL::DEBUGGER #<SYMBOL-PACKAGE-LOCKED-ERROR "setting the value of ~S" {1004FC3873}> #<FUNCTION CL-REPL::DEBUGGER>)
11: (SB-DEBUG::RUN-HOOK *DEBUGGER-HOOK* #<SYMBOL-PACKAGE-LOCKED-ERROR "setting the value of ~S" {1004FC3873}>)
12: (INVOKE-DEBUGGER #<SYMBOL-PACKAGE-LOCKED-ERROR "setting the value of ~S" {1004FC3873}>)
13: (CERROR "Ignore the package lock." SYMBOL-PACKAGE-LOCKED-ERROR :PACKAGE #<PACKAGE "COMMON-LISP"> :FORMAT-CONTROL "setting the value of ~S" :FORMAT-ARGUMENTS (VALUES) :SYMBOL VALUES :REFERENCES ((:SBCL :NODE "Package Locks") (:ANSI-CL :SECTION (11 1 2 1 2))))
14: (PACKAGE-LOCK-VIOLATION #<PACKAGE "COMMON-LISP"> :SYMBOL VALUES :FORMAT-CONTROL "setting the value of ~S" :FORMAT-ARGUMENTS (VALUES))
15: (SB-KERNEL:ASSERT-SYMBOL-HOME-PACKAGE-UNLOCKED VALUES "setting the value of ~S")
16: (SB-INT:ABOUT-TO-MODIFY-SYMBOL-VALUE VALUES SET (19) NIL)
17: (SET VALUES (19))
18: (CL-REPL::EVAL-PRINT (+ (* 3 5) 4))
19: (CL-REPL::READ-EVAL-PRINT)
20: (CL-REPL::REPL :PACKAGE #<unused argument> :LEVEL 0 :KEYMAP "default")
21: (CL-REPL:MAIN NIL :SHOW-LOGO T)
22: (SB-INT:SIMPLE-EVAL-IN-LEXENV (APPLY (QUOTE ROS.SCRIPT.CL-REPL.3724301384::MAIN) ROSWELL:*ARGV*) #<NULL-LEXENV>)
23: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ROSWELL:QUIT (APPLY (QUOTE ROS.SCRIPT.CL-REPL.3724301384::MAIN) ROSWELL:*ARGV*)) #<NULL-LEXENV>)
24: (EVAL-TLF (ROSWELL:QUIT (APPLY (QUOTE ROS.SCRIPT.CL-REPL.3724301384::MAIN) ROSWELL:*ARGV*)) NIL NIL)
25: ((LABELS SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (ROSWELL:QUIT (APPLY (QUOTE ROS.SCRIPT.CL-REPL.3724301384::MAIN) ROSWELL:*ARGV*)) NIL)
26: (SB-INT:LOAD-AS-SOURCE #<CONCATENATED-STREAM :STREAMS NIL {1002E5FB43}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
27: ((FLET SB-FASL::THUNK :IN LOAD))
28: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<CLOSURE (FLET SB-FASL::THUNK :IN LOAD) {19FF53B}> #<CONCATENATED-STREAM :STREAMS NIL {1002E5FB43}>)
29: ((FLET SB-FASL::LOAD-STREAM :IN LOAD) #<CONCATENATED-STREAM :STREAMS NIL {1002E5FB43}> NIL)
30: (LOAD #<CONCATENATED-STREAM :STREAMS NIL {1002E5FB43}> :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
31: ((FLET ROSWELL::BODY :IN ROSWELL:SCRIPT) #<SB-SYS:FD-STREAM for "file /Users/murray/.roswell/bin/cl-repl" {1002E5B183}>)
32: (ROSWELL:SCRIPT "/Users/murray/.roswell/bin/cl-repl")
33: (ROSWELL:RUN ((:EVAL "(ros:quicklisp)") (:SCRIPT "/Users/murray/.roswell/bin/cl-repl") (:QUIT NIL)))
34: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ROSWELL:RUN (QUOTE ((:EVAL "(ros:quicklisp)") (:SCRIPT "/Users/murray/.roswell/bin/cl-repl") (:QUIT NIL)))) #<NULL-LEXENV>)
35: (EVAL (ROSWELL:RUN (QUOTE ((:EVAL "(ros:quicklisp)") (:SCRIPT "/Users/murray/.roswell/bin/cl-repl") (:QUIT NIL)))))
36: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:EVAL . "(progn #-ros.init(cl:load \"/usr/local/Cellar/roswell/18.1.10.87/etc/roswell/init.lisp\"))") (:EVAL . "(ros:run '((:eval\"(ros:quicklisp)\")(:script \"/Users/murray/.roswell/bin/cl-repl\")(:quit ())))")))
37: (SB-IMPL::TOPLEVEL-INIT)
38: ((FLET SB-UNIX::BODY :IN SAVE-LISP-AND-DIE))
39: ((FLET "WITHOUT-INTERRUPTS-BODY-36" :IN SAVE-LISP-AND-DIE))
40: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))

Lock on package COMMON-LISP violated when setting the value of VALUES while in
package COMMON-LISP-USER.
See also: The SBCL Manual, Node "Package Locks" The ANSI Standard, Section 11.1.2.1.2
 [Condition of type SYMBOL-PACKAGE-LOCKED-ERROR]

Any suggestions?

Thanks!

Murray

**Comment by koji-kojiro** [comment]
hmm...
I cannot reproduce that on my PC.
The error seems to occur due to name conflict between `cl:values` and `cl-repl::values`, but as far as I know, there's no such conflict.
Can you try the newest version (v0.6.0) and report again?

**Comment by koji-kojiro** [comment]
Maybe fixed. (10a485c0487332c0fa85f6d1f107a2f3c4650d85)

**Comment by m-bob** [comment]
I'm having difficulty updating cl-repl. In fact, it looks like the
installation procedure doesn't work properly for me. You'll see a (fatal)
error when I try to install -- but something gets installed.

This is what happens:

12:29:17 ~ 504 >  ros update koji-kojiro/cl-repl
no update function for koji-kojiro/cl-repl

12:29:54 ~ 505 >  ros delete koji-kojiro/cl-repl
koji-kojiro/cl-repl is not installed.


__________________________________________________________

12:30:09 ~ 506 >  ros install koji-kojiro/cl-repl
Installing from github koji-kojiro/cl-repl
To load "cl-repl":
  Load 1 ASDF system:
    cl-repl
; Loading "cl-repl"
..
; compiling file
"/Users/murray/.roswell/local-projects/koji-kojiro/cl-repl/src/package.lisp"
(written 10 FEB 2018 04:33:48 PM):
; compiling (IN-PACKAGE :CL-USER)
; compiling (DEFPACKAGE :CL-REPL ...)
; compiling (DEFPACKAGE :REPL-USER ...)

;
/Users/murray/.cache/common-lisp/sbcl-1.4.4-macosx-x64/Users/murray/.roswell/local-projects/koji-kojiro/cl-repl/src/package-tmp5GEXGEG5.fasl
written
; compilation finished in 0:00:00.003
; compiling file
"/Users/murray/.roswell/local-projects/koji-kojiro/cl-repl/src/color.lisp"
(written 10 FEB 2018 04:33:48 PM):
; compiling (IN-PACKAGE CL-REPL)
; compiling (DEFUN COLOR ...)
; compiling (DEFPARAMETER *DEFAULT-PROMPT-COLOR* ...)
; compiling (DEFPARAMETER *DEBUGGER-PROMPT-COLOR* ...)
; compiling (DEFPARAMETER *LOGO-COLOR* ...)
; compiling (DEFPARAMETER *OUTPUT-INDICATOR-COLOR* ...)
; compiling (DEFPARAMETER *SPLASH-COLOR* ...)
; compiling (DEFPARAMETER *CONDITION-COLOR* ...)
; compiling (DEFPARAMETER *SECTION-COLOR* ...)
; compiling (DEFPARAMETER *MESSAGE-COLOR* ...)
; compiling (DEFPARAMETER *STRING-SYNTAX-COLOR* ...)
; compiling (DEFPARAMETER *VARIABLE-SYNTAX-COLOR* ...)
; compiling (DEFPARAMETER *CONSTANT-SYNTAX-COLOR* ...)
; compiling (DEFPARAMETER *LAMBDA-SYNTAX-COLOR* ...)
; compiling (DEFPARAMETER *DEFINITION-SYNTAX-COLOR* ...)
; compiling (DEFPARAMETER *KEYWORD-SYNTAX-COLOR* ...)
; compiling (DEFPARAMETER *SPECIAL-SYNTAX-COLOR* ...)
; compiling (DEFPARAMETER *FUNCTION-SYNTAX-COLOR* ...)
; compiling (DEFPARAMETER *BOOLEAN-SYNTAX-COLOR* ...)
; compiling (DEFPARAMETER *NORMAL-SYNTAX-COLOR* ...)

;
/Users/murray/.cache/common-lisp/sbcl-1.4.4-macosx-x64/Users/murray/.roswell/local-projects/koji-kojiro/cl-repl/src/color-tmpAR3FSGEY.fasl
written
; compilation finished in 0:00:00.003
; compiling file
"/Users/murray/.roswell/local-projects/koji-kojiro/cl-repl/src/color-scheme.lisp"
(written 10 FEB 2018 04:33:48 PM):
; compiling (IN-PACKAGE :CL-REPL)
; compiling (DEFVAR *COLOR-SCHEMES* ...)
; compiling (DEFUN FIND-COLOR-SCHEME ...)
; compiling (DEFMACRO DEFINE-COLOR-SCHEME ...)
; compiling (DEFUN SET-COLOR ...)
; compiling (DEFUN COLOR-SCHEME ...)
; compiling (DEFINE-COLOR-SCHEME "default" ...)
; compiling (DEFINE-COLOR-SCHEME "off" ...)

;
/Users/murray/.cache/common-lisp/sbcl-1.4.4-macosx-x64/Users/murray/.roswell/local-projects/koji-kojiro/cl-repl/src/color-scheme-tmpJAIDFZTC.fasl
written
; compilation finished in 0:00:00.010
; compiling file
"/Users/murray/.roswell/local-projects/koji-kojiro/cl-repl/src/highlight.lisp"
(written 10 FEB 2018 04:33:48 PM):
; compiling (IN-PACKAGE :CL-REPL)
; compiling (DEFUN ESCAPE-NAME ...)
; compiling (DEFUN LIST-REGEX ...)
; compiling (DESTRUCTURING-BIND (FUNCTIONS SPECIALS) ...)
; compiling (DEFUN MAP-SYNTAX ...)
; compiling (DEFUN HIGHLIGHT-TEXT ...)
; compiling (DEFUN REDISPLAY-WITH-HIGHLIGHT ...)
; compiling (DEFUN ENABLE-SYNTAX ...)
; compiling (DEFUN DISABLE-SYNTAX ...)

;
/Users/murray/.cache/common-lisp/sbcl-1.4.4-macosx-x64/Users/murray/.roswell/local-projects/koji-kojiro/cl-repl/src/highlight-tmp8V3J6PE9.fasl
written
; compilation finished in 0:00:00.019
; compiling file
"/Users/murray/.roswell/local-projects/koji-kojiro/cl-repl/src/keymap.lisp"
(written 10 FEB 2018 04:33:48 PM):
; compiling (IN-PACKAGE :CL-REPL)
; compiling (DEFVAR *KEYMAPS* ...)
; compiling (DEFVAR *RL-DEFAULT-KEYMAP* ...)
; compiling (DEFMACRO DEFINE-KEYMAP ...)
; compiling (DEFUN UNBIND-KEY ...)
; compiling (DEFUN FIND-KEYMAP ...)
; compiling (DEFINE-KEYMAP "default" ...)
; compiling (DEFUN SET-KEYMAP ...)
; compiling (SET-KEYMAP "default")

;
/Users/murray/.cache/common-lisp/sbcl-1.4.4-macosx-x64/Users/murray/.roswell/local-projects/koji-kojiro/cl-repl/src/keymap-tmp9V47YWQF.fasl
written
; compilation finished in 0:00:00.009
; compiling file
"/Users/murray/.roswell/local-projects/koji-kojiro/cl-repl/src/command.lisp"
(written 10 FEB 2018 04:33:48 PM):
; compiling (IN-PACKAGE :CL-REPL)
; compiling (DEFVAR *MAGIC-COMMANDS* ...)
; compiling (DEFMACRO DEFINE-MAGIC ...)
; compiling (DEFMACRO MESSAGE-FROM-MAGIC ...)
; compiling (DEFUN INVOKE-MAGIC ...)
; compiling (DEFUN INPUT-MAGIC-P ...)
; compiling (DEFINE-MAGIC RUN ...)
; compiling (DEFUN EDIT-FILE-AND-READ ...)
; compiling (DEFINE-MAGIC EDIT ...)
; compiling (DEFINE-MAGIC CD ...)
; compiling (DEFINE-MAGIC TIME ...)
; compiling (DEFINE-MAGIC LOAD ...)
; compiling (DEFINE-MAGIC PACKAGE ...)
; compiling (DEFINE-MAGIC HELP ...)

;
/Users/murray/.cache/common-lisp/sbcl-1.4.4-macosx-x64/Users/murray/.roswell/local-projects/koji-kojiro/cl-repl/src/command-tmp9BN22RMA.fasl
written
; compilation finished in 0:00:00.038
; compiling file
"/Users/murray/.roswell/local-projects/koji-kojiro/cl-repl/src/shell.lisp"
(written 10 FEB 2018 04:33:48 PM):
; compiling (IN-PACKAGE :CL-REPL)
; compiling (DEFUN SHELL-COMMAND-P ...)
; compiling (DEFUN RUN-SHELL-COMMAND ...)

;
/Users/murray/.cache/common-lisp/sbcl-1.4.4-macosx-x64/Users/murray/.roswell/local-projects/koji-kojiro/cl-repl/src/shell-tmp1CXFJSK9.fasl
written
; compilation finished in 0:00:00.002
; compiling file
"/Users/murray/.roswell/local-projects/koji-kojiro/cl-repl/src/completer.lisp"
(written 10 FEB 2018 04:33:48 PM):
; compiling (IN-PACKAGE :CL-REPL)
; compiling (DEFUN GET-PACKAGE-FOR-SEARCH ...)
; compiling (DEFUN LIST-EXTERNAL-SYMBOLS ...)[1/3] System 'cl-repl' found.
Loading the system..

; file:
/Users/murray/.roswell/local-projects/koji-kojiro/cl-repl/src/completer.lisp
; in: DEFUN LIST-EXTERNAL-SYMBOLS
;     (DEFUN CL-REPL::LIST-EXTERNAL-SYMBOLS (CL-REPL::SYM-NAME
CL-REPL::PKG-NAME)
;       (LOOP :FOR CL-REPL::SYM :BEING :THE :EXTERNAL-SYMBOLS :OF
(FIND-PACKAGE
;
 CL-REPL::PKG-NAME)
;             :COLLECT (FORMAT NIL "~(~a:~a~)" CL-REPL::PKG-NAME
CL-REPL::SYM)))
; --> PROGN SB-IMPL::%DEFUN SB-IMPL::%DEFUN SB-INT:NAMED-LAMBDA
; ==>
;   #'(SB-INT:NAMED-LAMBDA CL-REPL::LIST-EXTERNAL-SYMBOLS
;         (CL-REPL::SYM-NAME CL-REPL::PKG-NAME)
;       (BLOCK CL-REPL::LIST-EXTERNAL-SYMBOLS
;         (LOOP :FOR CL-REPL::SYM :BEING :THE :EXTERNAL-SYMBOLS :OF
(FIND-PACKAGE
;
 CL-REPL::PKG-NAME)
;               :COLLECT (FORMAT NIL "~(~a:~a~)" CL-REPL::PKG-NAME
;                                CL-REPL::SYM))))
;
; caught STYLE-WARNING:
;   The variable SYM-NAME is defined but never used.

; compiling (DEFUN LIST-INTERNAL-SYMBOLS ...)
; file:
/Users/murray/.roswell/local-projects/koji-kojiro/cl-repl/src/completer.lisp
; in: DEFUN LIST-INTERNAL-SYMBOLS
;     (DEFUN CL-REPL::LIST-INTERNAL-SYMBOLS (CL-REPL::SYM-NAME
CL-REPL::PKG-NAME)
;       (LOOP :FOR CL-REPL::SYM :BEING :THE :SYMBOLS :OF (FIND-PACKAGE
;                                                         CL-REPL::PKG-NAME)
;             :COLLECT (FORMAT NIL "~(~a::~a~)" CL-REPL::PKG-NAME
CL-REPL::SYM)))
; --> PROGN SB-IMPL::%DEFUN SB-IMPL::%DEFUN SB-INT:NAMED-LAMBDA
; ==>
;   #'(SB-INT:NAMED-LAMBDA CL-REPL::LIST-INTERNAL-SYMBOLS
;         (CL-REPL::SYM-NAME CL-REPL::PKG-NAME)
;       (BLOCK CL-REPL::LIST-INTERNAL-SYMBOLS
;         (LOOP :FOR CL-REPL::SYM :BEING :THE :SYMBOLS :OF (FIND-PACKAGE
;
CL-REPL::PKG-NAME)
;               :COLLECT (FORMAT NIL "~(~a::~a~)" CL-REPL::PKG-NAME
;                                CL-REPL::SYM))))
;
; caught STYLE-WARNING:
;   The variable SYM-NAME is defined but never used.

; compiling (DEFUN LIST-SYMBOLS-AND-PACKAGES ...)
; file:
/Users/murray/.roswell/local-projects/koji-kojiro/cl-repl/src/completer.lisp
; in: DEFUN LIST-SYMBOLS-AND-PACKAGES
;     (DEFUN CL-REPL::LIST-SYMBOLS-AND-PACKAGES (CL-REPL::SYM-NAME)
;       (CONCATENATE 'LIST
;                    (LOOP :FOR CL-REPL::PKG :IN (LIST-ALL-PACKAGES)
;                          :APPEND (LOOP :FOR CL-REPL::NAME :IN
(PACKAGE-NICKNAMES
;
 CL-REPL::PKG)
;                                        :COLLECT (FORMAT NIL "~(~a:~)"
;                                                         CL-REPL::NAME))
;                          :COLLECT (FORMAT NIL "~(~a:~)"
;                                           (PACKAGE-NAME CL-REPL::PKG)))
;                    (LOOP :FOR CL-REPL::SYM :BEING :THE :SYMBOLS :OF
*PACKAGE*
;                          :COLLECT (STRING-DOWNCASE CL-REPL::SYM))
;                    (LOOP :FOR CL-REPL::KW :BEING :THE :SYMBOLS :OF
(FIND-PACKAGE
;
"KEYWORD")
;                          :COLLECT (FORMAT NIL ":~(~a~)" CL-REPL::KW))))
; --> PROGN SB-IMPL::%DEFUN SB-IMPL::%DEFUN SB-INT:NAMED-LAMBDA
; ==>
;   #'(SB-INT:NAMED-LAMBDA CL-REPL::LIST-SYMBOLS-AND-PACKAGES
;         (CL-REPL::SYM-NAME)
;       (BLOCK CL-REPL::LIST-SYMBOLS-AND-PACKAGES
;         (CONCATENATE 'LIST
;                      (LOOP :FOR CL-REPL::PKG :IN (LIST-ALL-PACKAGES)
;                            :APPEND (LOOP :FOR CL-REPL::NAME :IN #
;                                          :COLLECT #)
;                            :COLLECT (FORMAT NIL "~(~a:~)" #))
;                      (LOOP :FOR CL-REPL::SYM :BEING :THE :SYMBOLS :OF
*PACKAGE*
;                            :COLLECT (STRING-DOWNCASE CL-REPL::SYM))
;                      (LOOP :FOR CL-REPL::KW :BEING :THE :SYMBOLS :OF
(FIND-PACKAGE
;
"KEYWORD")
;                            :COLLECT (FORMAT NIL ":~(~a~)" CL-REPL::KW)))))
;
; caught STYLE-WARNING:
;   The variable SYM-NAME is defined but never used.

; compiling (DEFUN SELECT-COMPLETIONS ...)
; compiling (DEFUN COMPLETER ...)

;
/Users/murray/.cache/common-lisp/sbcl-1.4.4-macosx-x64/Users/murray/.roswell/local-projects/koji-kojiro/cl-repl/src/completer-tmpX4BRKI0R.fasl
written
; compilation finished in 0:00:00.063
WARNING:
   Lisp compilation had style-warnings while
   compiling #<CL-SOURCE-FILE "cl-repl" "src" "completer">
; compiling file
"/Users/murray/.roswell/local-projects/koji-kojiro/cl-repl/src/debugger.lisp"
(written 10 FEB 2018 04:33:48 PM):
; compiling (IN-PACKAGE :CL-REPL)
; compiling (DEFUN CONDITION-STRING ...)
; compiling (DEFUN DEBUGGER-BANNER ...)
; compiling (DEFVAR *CURRENT-CONDITION*)
; compiling (DEFVAR *INVOKABLE-RESTARTS*)
; compiling (DEFVAR *SELECTED-RESTART* ...)
; compiling (DEFUN DEBUGGER ...)
; compiling (DEFUN INVOKE-RESTART-BY-NUMBER ...)
; file:
/Users/murray/.roswell/local-projects/koji-kojiro/cl-repl/src/debugger.lisp
; in: DEFUN INVOKE-RESTART-BY-NUMBER
;     (LET ((CL-READLINE:*DONE* T))
;       (SETF CL-REPL::N (DIGIT-CHAR-P (CL-READLINE:READ-KEY))))
;
; caught STYLE-WARNING:
;   using the lexical binding of the symbol (CL-READLINE:*DONE*), not the
;   dynamic binding, even though the name follows
;   the usual naming convention (names like *FOO*) for special variables
;
; caught STYLE-WARNING:
;   The variable CL-READLINE:*DONE* is defined but never used.

; compiling (DEFUN SHOW-BACKTRACE ...)
; compiling (DEFINE-KEYMAP "debugger" ...)

;
/Users/murray/.cache/common-lisp/sbcl-1.4.4-macosx-x64/Users/murray/.roswell/local-projects/koji-kojiro/cl-repl/src/debugger-tmpQ371UGST.fasl
written
; compilation finished in 0:00:00.012
WARNING:
   Lisp compilation had style-warnings while
   compiling #<CL-SOURCE-FILE "cl-repl" "src" "debugger">
; compiling file
"/Users/murray/.roswell/local-projects/koji-kojiro/cl-repl/src/input.lisp"
(written 10 FEB 2018 04:33:48 PM):
; compiling (IN-PACKAGE :CL-REPL)
; compiling (DEFVAR *LAST-INPUT* ...)
; compiling (DEFUN CURRENT-PACKAGE ...)
; compiling (DEFVAR *DEFAULT-PROMPT-FUNCTION* ...)
; compiling (DEFVAR *DEBUGGER-PROMPT-FUNCTION* ...)
; compiling (DEFUN PROMPT ...)
; compiling (DEFUN LINE-CONTINUE-P ...)
; compiling (DEFUN CHECK-INPUT ...)
; compiling (DEFUN READ-INPUT1 ...)
; compiling (DEFUN READ-INPUT ...)

;
/Users/murray/.cache/common-lisp/sbcl-1.4.4-macosx-x64/Users/murray/.roswell/local-projects/koji-kojiro/cl-repl/src/input-tmp2OWI3Q7U.fasl
written
; compilation finished in 0:00:00.013
; compiling file
"/Users/murray/.roswell/local-projects/koji-kojiro/cl-repl/src/repl.lisp"
(written 10 FEB 2018 04:33:48 PM):
; compiling (IN-PACKAGE :CL-REPL)
; compiling (DEFVAR *DEBUGGER-LEVEL* ...)
; compiling (DEFUN EXIT-WITH-PROMPT ...)
; compiling (DEFVAR *OUTPUT-INDICATOR-FUNCTION* ...)
; compiling (DEFUN PRINT-RESULT ...)
; compiling (DEFUN EVAL-PRINT ...)
; file:
/Users/murray/.roswell/local-projects/koji-kojiro/cl-repl/src/repl.lisp
; in: DEFUN EVAL-PRINT
;     (SETQ VALUES (MULTIPLE-VALUE-LIST (EVAL -)))
; ==>
;   (SET 'VALUES (MULTIPLE-VALUE-LIST (EVAL -)))
;
; caught WARNING:
;   violating package lock on COMMON-LISP:VALUES

; compiling (DEFUN READ-EVAL-PRINT ...)
; file:
/Users/murray/.roswell/local-projects/koji-kojiro/cl-repl/src/repl.lisp
; in: DEFUN READ-EVAL-PRINT
;     (DEFUN CL-REPL::READ-EVAL-PRINT ()
;       (LET ((*DEBUGGER-HOOK* #'CL-REPL::DEBUGGER))
;         (RESTART-CASE (CL-REPL::EVAL-PRINT (SETQ #))
;           (CL-REPL::*ABORT NIL :REPORT "Deduce debugger level." T)
;           (CL-REPL::*EXIT NIL :REPORT "Exit CL-REPL." (THROW 0 NIL))
;           (CL-REPL::*RETRY NIL :REPORT "Try evaluating again."
;            (CL-REPL::EVAL-PRINT -)))))
; --> PROGN
; ==>
;   (SB-IMPL::%DEFUN 'CL-REPL::READ-EVAL-PRINT
;                    (SB-INT:NAMED-LAMBDA CL-REPL::READ-EVAL-PRINT
;                        NIL
;                      (BLOCK CL-REPL::READ-EVAL-PRINT
;                        (LET (#)
;                          (RESTART-CASE #
;                            #
;                            #
;                            #)))))
;
; caught STYLE-WARNING:
;   Using 0 of type (INTEGER 0 0) as a catch tag (which tends to be
unportable
;   because THROW and CATCH use EQ comparison)

; compiling (DEFUN REPL ...)
; file:
/Users/murray/.roswell/local-projects/koji-kojiro/cl-repl/src/repl.lisp
; in: DEFUN REPL
;     (DEFUN CL-REPL::REPL
;            (&KEY PACKAGE (CL-REPL::LEVEL 0) (CL-REPL::KEYMAP "default"))
;       (LOOP :WITH CL-REPL:*DEBUGGER-LEVEL* := CL-REPL::LEVEL
;             :DO (CL-REPL::SET-KEYMAP CL-REPL::KEYMAP)
;             :WHILE (CATCH CL-REPL::LEVEL (CL-REPL::READ-EVAL-PRINT))))
; --> PROGN SB-IMPL::%DEFUN SB-IMPL::%DEFUN SB-INT:NAMED-LAMBDA
; ==>
;   #'(SB-INT:NAMED-LAMBDA CL-REPL::REPL
;         (&KEY PACKAGE (CL-REPL::LEVEL 0) (CL-REPL::KEYMAP "default"))
;       (BLOCK CL-REPL::REPL
;         (LOOP :WITH CL-REPL:*DEBUGGER-LEVEL* := CL-REPL::LEVEL
;               :DO (CL-REPL::SET-KEYMAP CL-REPL::KEYMAP)
;               :WHILE (CATCH CL-REPL::LEVEL (CL-REPL::READ-EVAL-PRINT)))))
;
; caught STYLE-WARNING:
;   The variable PACKAGE is defined but never used.


;
/Users/murray/.cache/common-lisp/sbcl-1.4.4-macosx-x64/Users/murray/.roswell/local-projects/koji-kojiro/cl-repl/src/repl-tmp9KKTJMYV.fasl
written
; compilation finished in 0:00:00.016
;
; compilation unit aborted
;   caught 1 fatal ERROR condition
;   caught 1 WARNING condition
;   caught 7 STYLE-WARNING conditions
[2/3] Processing build-hook..
[3/3] Attempting to install the scripts in roswell/ subdirectory of the
system...
Found 2 scripts: cl-repl ros-repl
/Users/murray/.roswell/bin/cl-repl
/Users/murray/.roswell/bin/ros-repl
up to date. stop

__________________________________________________________

But after (re-) installation, it still shows that I have cl-repl 0.5.0 and
it still behaves as before.

Yours

Murray

**Comment by koji-kojiro** [comment]
Please check `~/.roswell/local-projects/koji-kojiro/cl-repl` .
If it is updated, launch the repl and check whether the bug still remains or not.
I think it was correctly updated, and the messages can be negligible.

**Comment by m-bob** [comment]
It now works without error! Thank you!

I did three things:
[1] Manually deleted the cl-repl subdirectory in the directory ~/.roswell/local-projects/koji-kojiro/
[2] Updated cl-repl using ros: ros install koji-kojiro/cl-repl
[3] Made sure that my path contains the directory /Users/murray/.roswell/bin/

When I invoke cl-repl, I'm now getting version 0.6.1 and it's working properly.

Again, thank you!
