### ISSUE TITLE
Can't run after installing

### ISSUE THREAD

**Issue by oscu0** [koji-kojiro/cl-repl#37]
macOS 10.13.3
Installed Roswell through brew, linked `readline`. `cl-repl` is not found, `ros repl` returns `script repl doesn't exist`

**Comment by oscu0** [comment]
Update: I can run it by running the binary in `~/.roswell/bin`, and I can run it normally after adding that directory to `$PATH`. It's possible something on my end necessitated the extra step, but I'm not sure. Perhaps add it to the readme anyway?
Here's my PATH from `.zshrc`:
`PATH="$PATH:$HOME/anaconda3/bin:$HOME/.roswell/bin:/usr/bin:/bin:/usr/sbin:/sbin"`

**Comment by koji-kojiro** [comment]
I'll update README.
FYI, that is documented on [roswell's wiki page](https://github.com/roswell/roswell/wiki/Roswell-as-a-Scripting-Environment), though it's a bit difficult to find.

Thanks.
