### ISSUE TITLE
Sockets and Threads

### ISSUE THREAD

**Issue by silent-entertainment** [koji-kojiro/cl-repl#52]
I'm trying to get an http server running on CL REPL Android, and I'm having difficulty. 

CL REPL is up to date,  from Play Store.

I installed quicklisp via CL REPL, and it seems to be working. 

I tried aserve, but that failed due to a missing ACL-COMPAT error.

I tried hunchentoot and hunchentoot-test. For hunchentoot, after starting the service the REPL drops into the debugger,  only saying,  "Top level in: #<process hunchentoot-listener-*:4242 0xb60ed5c0>." This seems to indicate that it's running, but Firefox can't connect at 127.0.0.1:4242 per the hunchentoot documentation. I also tried going to localhost:4242, with three same result. 

hunchentoot-test didn't show any errors, but Firefox can't connect. 

I do have some experience with hunchentoot on a Linux box, years ago. 

Before attempting the installation I did try to research ECL and EQL5 feature implementations and missing features, and I looked for reports from anyone who successfully ran an http server on CL ECL for Android. Other than the ECL documentation about threads, I found zero information. 

Are there any known related issues?

Edit: Sorry, I accidentally submitted the issue before i was finished.

**Comment by silent-entertainment** [comment]
Oops! More information.

After exiting the debugger, the output says, 

"
CONDITION OF TYPE: UNKNOWN-ERROR
The condition The function USOCKET::FDSET-ALLOC is undefined. occurred with errno 0.
"

**Comment by koji-kojiro** [comment]
This project is 'cl-repl'. The app mentioned here is 'CL REPL'. Two of these are different and not relevant.

**Comment by vindarel** [comment]
@silent-entertainment you meant https://www.lights-of-holiness.eu/cl-repl/ I suppose ?
